# Generated by Django 5.2.7 on 2026-01-17 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_add_disable_activity_logging'),
        ('users', '0004_alter_user_location_country'),
    ]

    operations = [
    ]
