version: "3"

services:
  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - DEVELOPMENT_MODE=True
    image: cinematacms/cinematacms-dev:latest
    volumes:
      - ./:/home/cinemata/cinematacms/
    command: "./deploy/docker/prestart.sh"
    environment:
      DEVELOPMENT_MODE: True
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_SHORT: 'no'
      ENABLE_CELERY_LONG: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ADMIN_USER: 'admin'
      ADMIN_EMAIL: 'admin@localhost'
      ADMIN_PASSWORD: 'admin'
    depends_on:
      - redis
      - db
    networks:
      - cinemata_network
  frontend:
    image: node:20
    volumes:
      - ${PWD}/frontend:/home/cinemata/cinematacms/frontend/
    working_dir: /home/cinemata/cinematacms/frontend/
    command: bash -c "npm install && npm run start"
    env_file:
      - ${PWD}/frontend/.env
    ports:
      - "8088:8088"
    depends_on:
      - web
    networks:
      - cinemata_network
  web:
    image: cinematacms/cinematacms-dev:latest
    command: "python manage.py runserver 0.0.0.0:80"
    environment:
      DEVELOPMENT_MODE: True
    ports:
      - "80:80"
    volumes:
      - ./:/home/cinemata/cinematacms/
    depends_on:
      - migrations
    networks:
      - cinemata_network
  db:
    image:  postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: cinematacms
      POSTGRES_PASSWORD: cinematacms
      POSTGRES_DB: cinematacms
      TZ: Europe/London
    networks:
      - cinemata_network
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    volumes:
      - redis_data:/data
    networks:
      - cinemata_network
    ports:
      - "6379:6379"
  celery_worker:
    image: cinematacms/cinematacms-dev:latest
    deploy:
      replicas: 1
    volumes:
      - ./:/home/cinemata/cinematacms/
    environment:
      ENABLE_UWSGI: 'no'
      ENABLE_NGINX: 'no'
      ENABLE_CELERY_BEAT: 'no'
      ENABLE_MIGRATIONS: 'no'
      DEVELOPMENT_MODE: True
    depends_on:
      - web
    networks:
      - cinemata_network

volumes:
  postgres_data:
  redis_data:

networks:
  cinemata_network:
    driver: bridge