
services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/

    environment:
      POSTGRES_USER: cinematacms
      POSTGRES_PASSWORD: cinematacms
      POSTGRES_DB: cinematacms
      TZ: Europe/London
    ports:
      - "5432:5432"
    networks:
      - cinemata_network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
       TZ: Europe/London
    networks:
      - cinemata_network


volumes:
  postgres_data:
  redis_data:

networks:
  cinemata_network:
    driver: bridge