# Generated by Django 5.2.17 on 2026-10-09 09:16

from django.db import migrations

import actions.fields


class Migration(migrations.Migration):
    dependencies = [
        ("actions", "0004_alter_mediaaction_remote_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaaction",
            name="remote_ip",
            field=actions.fields.MaskedIPField(blank=True, max_length=64, null=True),
        ),
    ]
