# Generated by Django 5.2 on 2026-09-01

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(
            name="EmailDeliveryReceipt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("delivery_id", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("recipient_ref", models.CharField(db_index=True, max_length=80)),
                (
                    "email_kind",
                    models.CharField(
                        choices=[
                            ("activity_notification", "Activity notification"),
                            ("media_lifecycle", "Media lifecycle"),
                            ("role_change", "Role change"),
                            ("account", "Account"),
                            ("authentication", "Authentication"),
                            ("contact_form", "Contact form"),
                            ("administrative", "Administrative"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("retrying", "Retrying"),
                            ("smtp_accepted", "SMTP accepted"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                            ("unknown", "Unknown"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("celery_task_id", models.CharField(blank=True, max_length=255)),
                ("reason_code", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [models.Index(fields=["status", "updated_at"], name="email_state_updated_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["queued", "sending", "retrying", "smtp_accepted", "failed", "skipped", "unknown"],
                            )
                        ),
                        name="email_receipt_valid_status",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "email_kind__in",
                                [
                                    "activity_notification",
                                    "media_lifecycle",
                                    "role_change",
                                    "account",
                                    "authentication",
                                    "contact_form",
                                    "administrative",
                                ],
                            )
                        ),
                        name="email_receipt_valid_kind",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("attempt_count__lte", 4)), name="email_receipt_attempt_limit"
                    ),
                ],
            },
        ),
    ]
