# Generated by Django 5.2.6 on 2025-10-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_language_code_alter_language_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_country',
            field=models.CharField(blank=True, choices=[('AQ', 'Antarctica'), ('AU', 'Australia'), ('BD', 'Bangladesh'), ('BT', 'Bhutan'), ('BU', 'Bougainville'), ('BN', 'Brunei Darussalam'), ('KH', 'Cambodia'), ('CN', 'China'), ('EG', 'Egypt'), ('FJ', 'Fiji'), ('PF', 'French Polynesia'), ('GU', 'Guam'), ('HA', 'Hawaii'), ('HK', 'Hong Kong'), ('IN', 'India'), ('ID', 'Indonesia'), ('XX', 'International'), ('JP', 'Japan'), ('KI', 'Kiribati'), ('KP', "Korea, Democratic People's Republic Of"), ('LA', 'Laos'), ('MY', 'Malaysia'), ('MV', 'Maldives'), ('MH', 'Marshall Islands'), ('FM', 'Micronesia, Federated States Of'), ('MN', 'Mongolia'), ('MM', 'Myanmar'), ('NR', 'Nauru'), ('NP', 'Nepal'), ('NC', 'New Caledonia'), ('NZ', 'New Zealand'), ('MP', 'Northern Mariana Islands'), ('PK', 'Pakistan'), ('PW', 'Palau'), ('PG', 'Papua New Guinea'), ('PH', 'Philippines'), ('PN', 'Pitcairn'), ('WS', 'Samoa'), ('SG', 'Singapore'), ('SB', 'Solomon Islands'), ('LK', 'Sri Lanka'), ('TW', 'Taiwan'), ('TH', 'Thailand'), ('TI', 'Tibet'), ('TL', 'Timor-Leste'), ('TK', 'Tokelau'), ('TO', 'Tonga'), ('TV', 'Tuvalu'), ('VU', 'Vanuatu'), ('VN', 'Viet Nam'), ('WP', 'West Papua'), ('KR', 'South Korea')], db_index=True, default='en', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_language',
            field=models.CharField(blank=True, db_index=True, default='en', max_length=35, null=True),
        ),
    ]
