# Generated by Django 5.2.7 on 2025-10-21 14:37

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_alter_media_media_country_alter_media_media_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagepopup',
            name='popup',
            field=models.FileField(help_text='3:4 aspect ratio preferred. WebP under 200 KB recommended (JPEG/PNG accepted). Auto-resized to 540px width.', max_length=500, upload_to='homepage-popups/', verbose_name='popup'),
        ),
        migrations.AlterField(
            model_name='indexpagefeatured',
            name='text',
            field=models.TextField(blank=True, help_text='Description text. HTML links allowed for internal URLs only (e.g., /about, /blog-post)', null=True, validators=[users.validators.validate_internal_html]),
        ),
    ]
