# Generated by Django 5.2.7 on 2026-01-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_featuredvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredvideo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
