# Generated by Django 5.2.7 on 2026-01-22 10:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0013_add_featured_date_field"),
        ("users", "0007_update_user_field_help_texts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["thumbnail"], name="idx_media_thumbnail"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["poster"], name="idx_media_poster"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["uploaded_thumbnail"], name="idx_media_uploaded_thumb"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["uploaded_poster"], name="idx_media_uploaded_poster"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["sprites"], name="idx_media_sprites"),
        ),
    ]
