# Generated by Django 5.2.7 on 2026-01-27 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_alter_featuredvideo_id'),
        ('files', '0014_add_thumbnail_field_indexes'),
    ]

    operations = [
    ]
