# Generated by Django 5.2.11 on 2026-03-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0020_populate_slugs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="password",
            field=models.CharField(blank=True, help_text="when video is in restricted state", max_length=256),
        ),
    ]
