# Generated by Django 5.2.13 on 2026-04-26 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0021_widen_password_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='media',
            name='media_user_state_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='media',
            name='media_user_encoding_idx',
        ),
    ]
