# Generated by Django 5.2.13 on 2026-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0026_media_comment_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="is_draft",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Draft uploads are kept private and excluded from the admin review queue until submitted.",
            ),
        ),
        migrations.AlterField(
            model_name="media",
            name="summary",
            field=models.TextField(help_text="Maximum 80 words", verbose_name="Synopsis"),
        ),
    ]
