# Generated by Django 5.2.17 on 2026-09-29 05:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0035_alter_media_media_file_alter_media_poster_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="analytics_revision",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.CreateModel(
            name="PlaybackSummary",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("revision", models.UUIDField()),
                ("context", models.CharField(max_length=8)),
                ("initiation", models.CharField(max_length=12)),
                ("started_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("duration_ms", models.PositiveIntegerField()),
                ("coverage", models.JSONField(default=list)),
                ("watch_days", models.JSONField(default=dict)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="playback_summaries", to="files.media"
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["media", "started_at"], name="files_playb_media_i_310ae2_idx")],
            },
        ),
    ]
