# Generated by Django 5.2.17 on 2026-09-29 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0036_media_analytics_revision_playbacksummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="analytics_revisions",
            field=models.JSONField(default=list, editable=False),
        ),
    ]
