# Generated by Django 5.2.17 on 2026-09-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0037_media_analytics_revisions"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySegmentMetric",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("day", models.DateField()),
                ("segment", models.CharField(max_length=12)),
                ("scope", models.CharField(max_length=32)),
                ("event", models.CharField(max_length=50)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("day", "segment", "scope", "event"), name="daily_segment_metric_unique"
                    )
                ],
            },
        ),
    ]
