# Generated by Django 5.2.17 on 2026-10-08 11:02

import django.db.models.functions.comparison
import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0038_dailysegmentmetric"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="communityimpact",
            options={
                "ordering": [
                    models.OrderBy(
                        django.db.models.functions.comparison.Coalesce(
                            "year", django.db.models.functions.datetime.ExtractYear("event_date")
                        ),
                        descending=True,
                    ),
                    "-event_date",
                    "-add_date",
                ]
            },
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="award_result",
            field=models.CharField(
                blank=True,
                choices=[("won", "Won"), ("nominated", "Nominated"), ("special_mention", "Special Mention")],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AU", "Australia"),
                    ("BD", "Bangladesh"),
                    ("BT", "Bhutan"),
                    ("BN", "Brunei Darussalam"),
                    ("BU", "Bougainville"),
                    ("KH", "Cambodia"),
                    ("CN", "China"),
                    ("FJ", "Fiji"),
                    ("PF", "French Polynesia"),
                    ("GU", "Guam"),
                    ("HA", "Hawaii"),
                    ("HK", "Hong Kong"),
                    ("IN", "India"),
                    ("ID", "Indonesia"),
                    ("JP", "Japan"),
                    ("KI", "Kiribati"),
                    ("KP", "Korea, Democratic People's Republic Of"),
                    ("KR", "South Korea"),
                    ("LA", "Laos"),
                    ("MY", "Malaysia"),
                    ("MV", "Maldives"),
                    ("MH", "Marshall Islands"),
                    ("FM", "Micronesia, Federated States Of"),
                    ("MN", "Mongolia"),
                    ("MM", "Myanmar"),
                    ("NR", "Nauru"),
                    ("NP", "Nepal"),
                    ("NC", "New Caledonia"),
                    ("NZ", "New Zealand"),
                    ("MP", "Northern Mariana Islands"),
                    ("PK", "Pakistan"),
                    ("PW", "Palau"),
                    ("PG", "Papua New Guinea"),
                    ("PH", "Philippines"),
                    ("PN", "Pitcairn"),
                    ("WS", "Samoa"),
                    ("SG", "Singapore"),
                    ("SB", "Solomon Islands"),
                    ("LK", "Sri Lanka"),
                    ("TW", "Taiwan"),
                    ("TH", "Thailand"),
                    ("TI", "Tibet"),
                    ("TL", "Timor-Leste"),
                    ("TK", "Tokelau"),
                    ("TO", "Tonga"),
                    ("TV", "Tuvalu"),
                    ("VU", "Vanuatu"),
                    ("VN", "Viet Nam"),
                    ("WP", "West Papua"),
                    ("AQ", "Antarctica"),
                    ("EG", "Egypt"),
                    ("XX", "International"),
                ],
                default="",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="creator",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="is_online",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="medium",
            field=models.CharField(
                blank=True,
                choices=[
                    ("film", "Film"),
                    ("artwork", "Artwork"),
                    ("music", "Song or Music"),
                    ("performance", "Performance"),
                    ("writing", "Writing"),
                    ("other", "Other"),
                ],
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="organiser",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="organiser_private",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="publication",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="communityimpact",
            name="year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="communityimpact",
            name="category",
            field=models.CharField(
                choices=[
                    ("screening", "Screened In"),
                    ("article", "Article or Review"),
                    ("referenced", "Referenced in Another Work"),
                    ("award", "Award"),
                    ("teaching", "Teaching or Research"),
                    ("featured", "Featured In"),
                    ("saves", "Saves & Playlists"),
                    ("academic", "Academic Usage"),
                    ("curated", "Curated Into"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
