# Generated by Django 5.2.17 on 2026-10-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationpreference",
            name="on_community_impact",
            field=models.CharField(
                choices=[("in_app", "In-App Only"), ("email", "In-App + Email"), ("none", "Disabled")],
                default="email",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("comment", "New comment on your media"),
                    ("reply", "Reply to your comment"),
                    ("like", "Someone liked your media"),
                    ("follow", "Someone followed you"),
                    ("mention", "You were mentioned in a comment"),
                    ("new_media", "New upload from someone you follow"),
                    ("added_to_playlist", "Your media was added to a playlist"),
                    ("community_impact", "A Community Impact record was added to your media"),
                    ("media_report", "Media was reported"),
                    ("system_announcement", "System announcement"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
